name: linter-test
on: push
jobs:
  build:


    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9"]


    steps:
      - name: linter-test
        run: |
          pip install poetry
          make lint

